#
# https://www.appveyor.com/docs/appveyor-yml
#

os: Visual Studio 2017

install:
  - set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
  # C:\projects\eventbus
  - echo %CD%
  # C:\projects\eventbus\EventBus
  - ps: cd EventBus
  - echo %CD%
  - git --version
  - git rev-list --count HEAD

# Disable patching assembly.info, it doesn't exists anymore
#assembly_info:
#  patch: true
#  file: AssemblyInfo.cs
#  assembly_version: "{version}"
#  assembly_file_version: '{version}'

build_script:
  - echo %CD%
  - msbuild EventBus.NetStandard.csproj /t:Rebuild /p:Configuration=Release
